extends Node2D

func _ready() -> void:
	%VoxelToggle.button_pressed = PerformanceSettingsSingleton.voxel_gi_enabled
	%VoxelToggle.toggled.connect(PerformanceSettingsSingleton.toggle_voxel_gi)

	%BloomToggle.button_pressed = PerformanceSettingsSingleton.bloom_enabled
	%BloomToggle.toggled.connect(PerformanceSettingsSingleton.toggle_bloom)

	%VolumetricFogToggle.button_pressed = PerformanceSettingsSingleton.volumetric_fog_enabled
	%VolumetricFogToggle.toggled.connect(PerformanceSettingsSingleton.toggle_volumetric_fog)

func _process(_delta: float) -> void:
	%FpsIndicator.text = "FPS: %d" % Engine.get_frames_per_second()
